name: Auto Compile Java to DEX

on:
  push:
    paths:
      - 'source/**/*.java'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Download android.jar
        run: |
          curl -L -o android.jar https://github.com/Sable/android-platforms/raw/master/android-30/android.jar

      - name: Compile Java
        run: |
          mkdir -p build_temp
          javac -cp android.jar -d build_temp source/*.java
          echo "âœ… Compilation done."

      - name: Convert to DEX
        run: |
          BUILD_TOOLS_VERSION=$(ls $ANDROID_SDK_ROOT/build-tools/ | tail -n 1)
          D8_PATH="$ANDROID_SDK_ROOT/build-tools/$BUILD_TOOLS_VERSION/d8"
          
          $D8_PATH --output source/ --lib android.jar build_temp/dex/mandre/*.class
          
          if [ -f source/classes.dex ]; then
            mv source/classes.dex source/MandreSettings.dex
          fi
      - name: Generate Random Message
        id: random_msg
        run: |
          if [ $((RANDOM % 2)) -eq 0 ]; then
            echo "MSG=<3" >> $GITHUB_OUTPUT
          else
            echo "MSG=</3" >> $GITHUB_OUTPUT
          fi

      - name: Commit and Push DEX
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ steps.random_msg.outputs.MSG }}
          file_pattern: 'source/*.dex'
